[workspace]
members = [
    "lion/lion_core",
    "lion/lion_capability",
    "lion/lion_concurrency",
    "lion/lion_isolation",
    "lion/lion_observability",
    "lion/lion_policy",
    "plugins/calculator"
]
resolver = "2"
