[workspace]
members = [
    "lion/core",
    "lion/capabilities",
    "lion/policy",
    "lion/isolation",
    "lion/concurrency",
    "lion/workflow",
    "lion/observability",
    "lion/runtime",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false